name: KAIMyEntitySaba-build-actions
on: [push]
jobs:
  build-gcc:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y cmake libbullet-dev libglu1-mesa-dev libx11-dev libxxf86vm-dev libxrandr-dev libxinerama-dev libxcursor-dev libxi-dev libglfw3-dev openjdk-8-jdk
      - name: build
        run: |
          git submodule update --init --recursive
          mkdir build
          cd build
          cmake ..
          make -j2
  build-clang:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y cmake libbullet-dev libglu1-mesa-dev libx11-dev libxxf86vm-dev libxrandr-dev libxinerama-dev libxcursor-dev libxi-dev libglfw3-dev openjdk-8-jdk
      - name: build
        env:
          C_COMPILER: clang
          CXX_COMPILER: clang++
        run: |
          git submodule update --init --recursive
          mkdir build
          cd build
          cmake ..
          make -j2
  build-ndk:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Android SDK Tools
        uses: android-actions/setup-android@v2
      - name: Install NDK
        run: |
          echo "y" | sudo ${ANDROID_HOME}/tools/bin/sdkmanager --install "ndk;24.0.8215888" --sdk_root=${ANDROID_SDK_ROOT} &> /dev/null
      - name: build
        run: |
          git submodule update --init --recursive
          ${ANDROID_HOME}/ndk/24.0.8215888/ndk-build NDK_PROJECT_PATH=. NDK_APPLICATION_MK=./Application.mk -j8
